# Generated by Django 2.2.27 on 2022-06-30 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20220625_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='love_bao',
            name='url_def',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
