# Generated by Django 2.2.27 on 2022-07-02 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20220701_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='love_bao',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
