# Generated by Django 2.2.27 on 2022-07-08 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20220702_2350'),
    ]

    operations = [
        migrations.RenameField(
            model_name='love_bao',
            old_name='rights_bao_des',
            new_name='right_bao_des',
        ),
    ]
